version: '3.4'

services:
  nodeapp:
    image: nodeapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes: 
      - ".:/usr/src/app"
    command: ["npm", "run", "debug"]
      