version: '3.4'

services:
  nodeapp:
    image: nodeapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - ".:/usr/src/app"
    command: ["npm", "start"]
